apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  name: sreday-2024-perses
  url: https://github.com/gnur/sreday-2024-perses.git
